### ISSUE TITLE
Patch submission/merging problems

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#149]
In submitting a patch for the LoC collection that contained both new period definitions and edits to existing collections, I noticed that the new definitions came through, but none of the edits did. The patch was based on a sync with the existing LoC collection in the main dataset, so these changes should have been recognized. I attach the IDB json file as txt here -- please compare to the LoC collection to see where the edits to existing definitions have not been recognized.

[periodo-LCSH_additions_3-1508681682650.txt](https://github.com/periodo/periodo-client/files/1404978/periodo-LCSH_additions_3-1508681682650.txt)

**Comment by rybesh** [comment]
The patch you submitted and merged only has the 130 new definitions. Are you sure you selected the 8 edited definitions (below the 130 new definitions) on the Submit Patch page? Clicking "Select all" below New Periods only selects the new periods, so you easily could have created a patch with only the new periods and not the edited ones. (Yes, this is a UI problem and will be fixed in the new interface.)

Using the DB you attached I was able to generate a patch with the edited periods, by scrolling past the new periods and selecting only the edited ones:
https://test.perio.do/#/patches/https://test.perio.do/patches/122/

**Comment by atomrab** [comment]
Ah, crud, that's exactly what happened. I didn't scroll down far enough. Thanks for the fix!
