### ISSUE TITLE
Redirect to show individual period collections / definitions in client

### ISSUE THREAD

**Issue by rybesh** [periodo/periodo-client#17]
Currently browsing to http://n2t.net/ark:/99152/p06xc6m redirects to https://test.perio.do/#6xc6m, which should load that period collection, but it doesn't. Instead https://test.perio.do/#periodCollections/p06xc6m/ shows the period collection.

Likewise http://n2t.net/ark:/99152/p06xc6mvjx2 redirects to https://test.perio.do/#6xc6mvjx2, which currently does nothing but should *also* show the period collection view with that period definition highlighted and scrolled to.

**Comment by ptgolden** [comment]
Fixed in 733efec95150c8a98d9fa56333bdd46a8f58b541. All valid pages in the client start with '#p/', which would never be a periodo identifier. When the client sees something that does not begin with '#p/', it will attempt to load the dataset from the current domain, check if the passed fragment is an ID of a period or period collection, and then redirect if that is the case.
