### ISSUE TITLE
Problem with map widget

### ISSUE THREAD

**Issue by ptgolden** [periodo/periodo-client#172]
When I load the period editing form, I get a blank blue box where the map should be, and lots of errors saying slight variations on:

```
regl.js:48 Error: (regl) bad data or missing for uniform "texture".  invalid texture type in command http://localhost:5002/periodo-client.js:225474:23 called from http://localhost:5002/periodo-client.js:225480:18
    at raise (regl.js:47)
    at Function.commandRaise (regl.js:390)
    at batch (eval at compile (regl.js:5549), <anonymous>:1017:66)
    at REGLCommand (regl.js:9432)
    at Array.<anonymous> (multi.js:109)
    at executeCallbacks (multi.js:186)
    at scope (eval at compile (regl.js:5549), <anonymous>:397:1)
    at REGLCommand (regl.js:9424)
    at frame (multi.js:214)
    at Function.scope (eval at compile (regl.js:5549), <anonymous>:353:1)
```

Any idea what's going on?

**Comment by rybesh** [comment]
It looks like the changes I made to fix this were lost somehow; specifically PR #165.

Or maybe you merged those changes into a different branch?

It looks like #163 was merged into master, but #164 was merged into the spatial-coverage-widget branch, and #165 was merged into the period-view-map branch.

This is probably my fault, because I generated PRs #164 and #165 against my earlier branches, not against master, so that they would only show what changed relative to those earlier PRs.

We might have an issue with #167 too for the same reason; looks like it was merged into the edit-broader-and-derived branch rather than master.

Anyway, we should be using resl to load the map tiles, and hopefully🤞 that will fix this issue.

Sorry for the version control headache; I should have been more explicit in my comments about how I had created the PRs… 😕

**Comment by ptgolden** [comment]
Ah cool. I noticed when I tried to merge one of the broader/narrower branches into master that a bunch of unrelated map stuff came in. I'll merge those later today.

**Comment by ptgolden** [comment]
K everything should be in now

**Comment by rybesh** [comment]
I'm still running into intermittent issues with the map. It seems to be a timing issue since it only happens sometimes. I think it has something to do with the interaction between React and substack's stuff (he never actually created an example of it working in React so I was kind of guessing at how to integrate it). The map tiles get loaded into blobs and the blob data is supplied to WebGL, but something seems to fuck up that process sometimes, resulting in the bad tile data errors. If you have any ideas about how to debug it, let me know. Otherwise I guess I'll appeal to substack for help…

**Comment by rybesh** [comment]
Another thing I'm noticing on the main browse page is that, even when the tiles are loading OK, there are some weird artifacts in the period detail view map when stepping through the list of periods. If I go from a period with spatial coverage features to one without spatial coverage features, the map from the previous period is still drawn to the screen, on top of (hiding) the info for the current period. Seems like the WebGL canvas is not being destroyed or hidden or whatever.

Until I can figure this out, a workaround might be to just show the blank map when there are no features.

**Comment by rybesh** [comment]
https://github.com/peermaps/mixmap/issues/5

**Comment by rybesh** [comment]
I seem to have fixed the issues with map tiles sometimes not loading, by re-creating the mixmap map component on each render. This has the unfortunate side effect of forcing the tiles to redraw every render, even if the viewbox hasn't changed, but I guess that is better than the tiles not loading at all.

The other problem  (ghost map drawn after DOM node is no longer there) is not fixed, so I reverted the period detail view to show the map even if there are no features (eventually every period should have features anyway).
