### ISSUE TITLE
Refreshing mergeURL after logging in from patch review

### ISSUE THREAD

**Issue by rybesh** [periodo/periodo-client#200]
9ea159fa8036ec1efc740877da46196cad53337c makes it so that non-logged-in users see a link to log in via ORCID, rather than non-functional comment/accept/reject controls.

However, even after logging in, we can't show the accept/reject controls because we don't have the mergeURL from the patch request `Link` header. Reloading the page re-fetches it and then you can see the accept/reject controls (if you have accept permissions), but it would be nice if we could somehow trigger the refresh after the login finishes. But I'm not sure what the best way to do that might be.

I guess this won't affect many people, so not a high priority …

**Comment by ptgolden** [comment]
Hmm.. fetching the patch happens in the resource's `loadData` method, which is called once, when the resource is initially mounted. It's the step when the checkboxes and loading indicators appear.

There's three options we could take here, from easiest to hardest:
1. Call `window.refresh()` after successfully logging in
2. Pass every resource a `reloadData` prop that can be called to run the `loadData` log again
3. Call `dispatch(PatchAction.GetPatchRequest)` after logging in, and add logic to the Review component to indicate that it's reloading the patch
4. Move all the data loading into the Review component itself, rather than have it in the resource. (This sucks)

I think (2) is a fine idea that could be useful in other contexts

**Comment by rybesh** [comment]
(2) sounds good to me too. 👍

**Comment by ptgolden** [comment]
Implemented in 3cae75abf661ec5c05b9d800c2739fe7dd69188d
