### ISSUE TITLE
Allow view and export of local authorities and definitions in various formats (CSV, JSON-LD, TTL)

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#209]
One of the strengths of the old interface was the way it allowed users to enter field data for new collections and definitions, and then see those immediately expressed as valid JSON-LD or TTL. This is useful for people who don't plan to submit their local datasets to PeriodO, but like the save function, it's not available in the new client. We should remember that there are likely to be users who just want to translate some period definitions to the PeriodO serialization format, especially if we imagine that other projects might want to use our format but not our data.

**Comment by rybesh** [comment]
What's the use case for this beyond what you could do with working JSON-LD export of local data sources?

A practical issue with this is that it means we need to have JSON-LD to TTL and CSV conversion in the client code, in addition to the JSON-LD to TTL (and soon CSV) conversion we have on the server, and they have to produce exactly the same output. There can be lots of small differences in different RDF stacks, unfortunately, so this is kind of a headache—we had a lot of old bugs that were due to issues with the client-side JSON-LD to TTL converter we were using in the old client.

**Comment by rybesh** [comment]
OK, this is working now. CSV and TTL are generated server-side.
