### ISSUE TITLE
Unable to open cursor when submitting changes in Safari

### ISSUE THREAD

**Issue by rybesh** [periodo/periodo-client#228]
Created a local database and editing it works fine in Safari now.

But, if you try to submit changes, you get this error:
![Screen Shot 2020-02-14 at 1 08 43 PM](https://user-images.githubusercontent.com/84592/74556141-5cf57680-4f2b-11ea-9464-2ea819e5c538.png)

Nothing appears in the JS console.

**Comment by ptgolden** [comment]
Can you confirm this is still happening? If it is, can I follow along with you submitting a patch in Safari? (With campus closed I have no access to a Mac).

**Comment by ptgolden** [comment]
We came to the conclusion that it was some combination of clauses in this query:

https://github.com/periodo/periodo-client/blob/60c569c2286299d5ffa5f76fc5542026e9b56b6e/modules/periodo-app/src/patches/actions.js#L183-L188

Using `keys` instead of `uniqueKeys` fixes things. And Safari is able to run `db.localBackendPatches.toCollection().uniqueKeys()` without an issue. Puzzling!

I'm not sure if there's a reason why `uniqueKeys` would need to be run instead of `keys`.. But even if that were the case, we can just create a new set out of the un-unique keys and be done with it.

**Comment by ptgolden** [comment]
This should not be an issue anymore after 98d5bdf0442cf1cc367918014b9fa3d43bb91e0a
