### ISSUE TITLE
Request for place gazetteer graph failing due to spurious redirect

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#234]
The following message appears when I try to load either the Canonical or a local data source:

<img width="954" alt="image" src="https://user-images.githubusercontent.com/4740995/76878568-0ab5b700-6843-11ea-929d-13538de96f73.png">

**Comment by rybesh** [comment]
Very weird; I can reproduce this on the deployed site but not when I run the same code locally. The request to get the place gazetteer is failing, but I can't determine why. I'll keep looking…

**Comment by rybesh** [comment]
OK, this is fixed. You'll need to [clear your cache](https://support.google.com/accounts/answer/32050?co=GENIE.Platform%3DDesktop&hl=en&oco=0) for it to start working again.

This was a caching issue. Somehow the server-side cache got corrupted, and was returning 303 See Other redirect to non-existent URL whenever the place gazetteer was requested. Clearing the server-side cache fixed that, but then the browser was using the cached 303 See Other response instead of making a new request. Clearing the browser cache then fixes that.

So if you encounter anyone who is getting this problem, have them clear their browser cache and it should work again. The browser cache only lasts for 7 days, so after 7 days from now, no one should encounter this problem—and only people who visited the site in the past day or two would have this problem in the first place.

I will set up a monitor that periodically requests the place gazetteer from the server, so that if the server-side cache becomes corrupted again we can catch it early.

**Comment by atomrab** [comment]
This seems to be fixed on my side. But it raises a question, which I'll ask in a separate issue.
