### ISSUE TITLE
Browser persistent storage isn't persistent anymore

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#235]
As the result of the previous issue, I went to clear my Chrome cache -- but found that my IDBs had already disappeared when I opened the client most recently, without me having deliberately cleared the cache. As far as I can tell, this isn't a result of any of my Chrome settings (none set to auto-clear cookies or browsing data), or of a software update to the computer. This doesn't seem to happen in Firefox. Is it something we should warn people about? I'm pretty sure I'd already merged all of the local IDBs I'd made, since I got paranoid about this after the last time this happened, so this isn't a problem at the moment -- but I can't figure out what is triggering it or how often it happens, which makes me nervous about future work (and about what will happen for other users, who will get pretty frustrated if their local collections keep disappearing). Any thoughts?

**Comment by rybesh** [comment]
I also had this happen recently. It seemed to have happened around the time that Chrome updated itself.

@ptgolden According to [this](https://dexie.org/docs/StorageManager) IndexedDB can be cleared by the browser under some circumstances like low disk space. I don't think that is what caused my IDBs to disappear, since I have > 400GB free, but maybe there are other reasons it gets cleared too. Do we need to be using StorageManager?

**Comment by rybesh** [comment]
Well, this turns out to be a bigger problem for us than expected:

> WebKit blog post announced changes to WebKit that erases all local storage data for a given site if the site is not used for seven days. Basically, you go on a vacation and the data is lost. This means that apps must necessarily keep the data on a server, or they risk losing it all because Apple thinks this equates to privacy.

https://andregarzia.com/2020/03/private-client-side-only-pwas-are-hard-but-now-apple-made-them-impossible.html

> Now ITP has aligned the remaining script-writable storage forms with the existing client-side cookie restriction, deleting all of a website’s script-writable storage after seven days of Safari use without user interaction on the site. 

https://webkit.org/blog/10218/full-third-party-cookie-blocking-and-more/

This means that in the short term the PeriodO client will not work in Safari, and since other browsers are also working toward this, eventually it will not work in any browser.

**Comment by rybesh** [comment]
I don't want to store user data on the server, but having some sort of persistence to a file seems absolutely necessary now if this is the way browsers are going.

It's annoying, but in the long run I think it is a good thing if people are clear about where their data is, and are able to look at the actual files.

The client could work mostly as it does now, except that when local changes are made we'd also need to update the local file, and to restore any missing IDBs from the files when coming back to the client after a while.

This obviously a non-trivial amount of work, though.

Any ideas for minimal steps we could take to keep PeriodO usable without completely rewriting the local storage stuff, @ptgolden?

**Comment by ptgolden** [comment]
The easiest immediate thing to do would be to package the client as an [Electron](https://github.com/electron/electron) application. This would make the data storage make more sense in terms of how people typically use computers ("Oh, this is an application I install, and my data is saved in it").

We would continue to deploy the client to the Web, but warn upon creating a local DB that the information isn't *really* persistent.

We also need to have a full import/export functionality, of course.

**Comment by ptgolden** [comment]
Sucks to rely heavily on Github releases, but that might be the easiest way to do [updates](https://www.electronjs.org/docs/tutorial/updates) with Electron.

**Comment by ptgolden** [comment]
<https://www.electron.build/> is worth looking into

**Comment by ptgolden** [comment]
Working on it now

**Comment by rybesh** [comment]
Reading about this again today, the [storage spec](https://storage.spec.whatwg.org/#persistence) seems to say pretty clearly that there *is* a way to grant permission for persistent storage that won't be cleared by the user agent. See also https://caniuse.com/#feat=mdn-api_storagemanager_persist

It seems like we should be able to ask the user for permission the first time they create a local editable database. Am I missing something here @ptgolden?

**Comment by ptgolden** [comment]
Oh, awesome. Good idea.

**Comment by ptgolden** [comment]
Can you check if it works in Safari? (See if `navigator.storage.persist` exists in the console)

**Comment by rybesh** [comment]
No, Safari doesn't support the StorageManager API, so `navigator.storage` doesn't exist. But both Chrome and FF support it.

According to [this recent article](https://web.dev/storage-for-the-web/#how-much) “Safari (both desktop and mobile) appears to allow up to 1GB. When the limit is reached, Safari will prompt the user, increasing the limit in 200MB increments. I was unable to find any official documentation on this.” I think now this only applies to sites that have been added to the home screen on iOS, but still holds for macOS.

**Comment by ptgolden** [comment]
I got this working in Firefox in 6b2e0b3, but it doesn't seem like it will work in Chrome, because..

> Persistent storage does not prompt the user in Chrome. Instead the browser uses latent metrics (is the page bookmarked, or does it have notifications permission granted for instance) to determine if the user is using the site sufficiently to allow storage to be persistent.

<https://groups.google.com/a/chromium.org/forum/#!topic/chromium-discuss/AWMgYFD_gJs>

Those latent metrics are:

> Initially, the permission was automatically granted to any sites that the user has bookmarked, and automatically denied otherwise. Beginning with Chrome 55, Chrome will automatically grant the persistence permission if any of the following are true:
>
> * The site is bookmarked (and the user has 5 or less bookmarks)
> * The site has high site engagement
> * The site has been added to home screen
> * The site has push notifications enabled

<https://developers.google.com/web/updates/2016/06/persistent-storage>

That seems pretty ridiculous set of criteria unless you happen to be a Google website. Lol.

**Comment by ptgolden** [comment]
Here's a good page from Dexie: <https://dexie.org/docs/StorageManager>

**Comment by rybesh** [comment]
I think this article has the most up-to-date information on storage manager, e.g. this on eviction policies: https://web.dev/storage-for-the-web/#eviction

**Comment by rybesh** [comment]
From the article above:

“Gone are the days of limited storage and prompting the user to store more and more data. Sites can store effectively all of the resources and data they need to run. Using the StorageManager API you can determine how much is available to you, and how much you've used. And with persistent storage, unless the user removes it, you can protect it from eviction.”

**Comment by ptgolden** [comment]
Right- I think the info found in that article has been generally my impression of browser storage since when we started PeriodO. The only change has been that browsers used to prompt when you tried to store some amount of data over some threshold (usually 5mb or so). (That's what the "gone are the days" refers to I imagine). The issue, to me, is the trend towards making local data storage less persistent, as evinced by the recent Safari decision and Adam's simultaneous opening of this issue.

There is the recent-ish addition of the `persisted()`/`persist()` API ("And with persistent storage, unless the user removes it, you can protect it from eviction"), but unfortunately, only one browser (Firefox) supports asking for it

**Comment by ptgolden** [comment]
The resolution we came to this afternoon:

If someone creates a local data source and `navigation.storage.persisted()` returns `false`:

1. In Firefox, we will call `navigation.storage.persist()` to prompt the browser to ask for permission to persistently store data
2. Otherwise, we will show a page that requires clicking an 'OK' button to continue. It will say something to the effect of:
    > Your browser does not currently allow https://client.perio.do/ to store persistent data on your machine. [Under certain circumstances](https://web.dev/storage-for-the-web/#eviction), such as your hard disk running low on space, any information you save in this local data source could be deleted.
    >
    > If you are running Google Chrome, you can enable persistent storage by enabling push notifications from https://client.perio.do/. We will not send you any push notifications, but they must be enabled in order to persist storage. >Enable push notifications<
    >
    > If you are running another browser, as of May 2020, there is no reliable way to ensure your data is persisted on the client. **If you add or edit periods in this backend and want them to be preserved, you should periodically either backup this data source or submit your work as a patch to a remote data source**.
    >
    > \>OK<

Additionally, if someone is working in a local data source and the `navigation.storage.persisted()` is `false`, there will be a bar across the top of the page notifying them that the data source should not be treated as persistent. That message can link to the page above.

**Comment by ptgolden** [comment]
Related: #191 (Sorry, Adam!)

**Comment by ptgolden** [comment]
All of the things in https://github.com/periodo/periodo-client/issues/235#issuecomment-627558138 were implemented in #252
