### ISSUE TITLE
Map resolution issues

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#290]
I really, really hate to look a gift horse in the mouth, but since we were having a similar issue with some views of the old map, I don't think it's my inland water obsession alone that is to blame.

The current map looks fantastic when fully zoomed out, and when zoomed in fairly close. But there is an intermediate zoom that is still excessively pixelated (you can see it if you browse and then select the Foundation of the Hellenic World collection, http://n2t.net/ark:/99152/p0339m9). I think it's two clicks in from maximum zoom out. Here's what it looks like when I select that collection on Chrome: 

![image](https://user-images.githubusercontent.com/4740995/87579045-f2dc2b80-c69a-11ea-9615-4ada6868371f.png)

**Comment by rybesh** [comment]
I generated a new set of tiles with slightly higher resolution at lower zoom levels. I also set the tile generation process to automatically rescale input pixel values, which changes the color palette of the tiles a bit, but seems to preserve detail better in e.g. the mountainous areas. Finally, since the deep blue ocean of the new tiles clashed with the deep purple we were using to highlight, I switched the highlight color to yellow.

Check it out and tell me what you think:
https://client.staging.perio.do/?page=backend-home&backendID=web-https%3A%2F%2Fdata.perio.do

**Comment by atomrab** [comment]
Looks good to me -- but have we checked accessibility issues in terms of
color schemes? We should probably use an accessible color picker for this,
right?

**Comment by rybesh** [comment]
You mean for the highlight colors?

Color picker tools generally are just looking for acceptable levels of contrast between the background and foreground. On a map, I'm not sure how to evaluate that since the background is multicolored. 

I don't think there is a form of color blindness that prevents distinguishing red from yellow, but I'm not sure.

**Comment by atomrab** [comment]
Yes, I do mean the highlight colors -- not so much yellow vs red, but the level of differentiation between the yellow and the green of the basemap. Would this help? https://colorbrewer2.org/

In any case, I am not at all well informed in this area and am happy to defer to you.

**Comment by rybesh** [comment]
Colorbrewer is for picking palettes of colors so that they are distinguishable, but in this case we have a semi-transparent overlay on top of a basemap with millions of different colors, so it doesn't really apply.

I took the current map looking at DINAA periods and converted to grayscale to give us a sense of the contrast under conditions of colorblindness:

<img width="827" alt="Screen Shot 2020-07-15 at 6 38 16 PM" src="https://user-images.githubusercontent.com/84592/87607124-9db80e00-c6ca-11ea-97fa-2f3965a674c0.png">

Seems OK to me?

**Comment by rybesh** [comment]
(Those highlights are yellow in the original, not red.)

**Comment by atomrab** [comment]
Yeah, I can see that. Let’s go for it, and if people complain about it, we
can always revisit.
