### ISSUE TITLE
Implement patch accept interface

### ISSUE THREAD

**Issue by ptgolden** [periodo/periodo-client#35]
Users are now able to submit patches, but they cannot yet be accepted

**Comment by atomrab** [comment]
In both Chrome and Firefox, clicking the "Submit patch" button causes a spinning processing icon to appear at the top of the page, but nothing happens on the user side after that. When one clicks on "Submitted patches", nothing appears. Should there be some event on the user-interface side to show that something has happened?

We tested this by adding a period (Pre-Pottery Neolithic A) to an existing collection (King and Stager) in local idbs entitled "test1" in both cases (in case something shows up on the server side).

**Comment by atomrab** [comment]
UPDATE: when we added a NEW collection (the British Museum thesaurus) with one new period, the "Submit Patch" produced the image below. The screen now includes the new collection (period itself not specified), the new period we'd previously added to an existing collection, and two periods that are listed as "edited" from the same existing collection that we're quite sure we did not just edit. It would be helpful in this case to see either a timestamp for the edit or some sort of view of the edits that had been made (I think this would be generally helpful, actually, for people to keep track of their own edits before submission, even if the bug is fixed). 

![submit_patch_capture](https://cloud.githubusercontent.com/assets/4740995/7257721/4e768bc8-e81d-11e4-9691-f122bd47cf62.JPG)

**Comment by atomrab** [comment]
UPDATE: submission of that patch (select all for new period collections and new periods) went through when I was logged in with my ORCID; "Submitted Patches" led to a page with the following message:

https://test.perio.do/patches/1/
Resolved? false

**Comment by ptgolden** [comment]
I'm going to create a new issue for things that don't have to do with accepting patches

**Comment by ptgolden** [comment]
Initial implementation in af1e5d4ba934f4b7167023614003ec0e8017b7a8. Not deployed yet.

**Comment by ptgolden** [comment]
Patch acceptance is now implemented. If there are problems with anything, we should include them in a new, separate issue.
