### ISSUE TITLE
JSON-LD/RDF view

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#56]
Is this going to reappear as a visualization option in this version of the client? Data model aside, it would help to surface some of the information we're hiding (e.g. if the language/script identifiers from the spreadsheet made it in or not). Also, it's good for letting people have a quick look at how the period definitions are structured in practice.

**Comment by ptgolden** [comment]
I forgot to add it back in, whoops

**Comment by ptgolden** [comment]
In terms of "information we're hiding", you can click on a period to see all the information there is about it.

**Comment by atomrab** [comment]
But are those original language tags in the serialized form? There must be something that tells you a label is in Ukrainian, since you're sorting by it, but it doesn't appear in the period view.

**Comment by ptgolden** [comment]
> But are those original language tags in the serialized form? 

I don't know what you're referring to.

The sort label is the "original label" value, i.e. what appeared in the text. If you think it should be something different, let me know.

**Comment by atomrab** [comment]
I think I didn't express myself well. In the spreadsheet, we had ISO codes
for the script and language of the original label. In the data model for
the current dataset, the original label has no language or script code (and
this is true when you look at the period definition info -- the alt label
is coded en-lat, the original label not).

But those ISO codes for the original labels must be preserved somewhere,
because you can now filter by language. I'm trying to figure out where
those are.

This is mainly because, if I understand the current data model correctly,
we need to add an additional language-coded altlabel to all
periods originally designated with non-English labels (since original label
has no language code). I can do this manually if necessary -- it's only a
couple of hundred -- but if those ISO codes are still there, maybe we could
do it programmatically.

Does this make sense, or am I misunderstanding something?

**Comment by ptgolden** [comment]
It makes sense.

> In the data model for the current dataset, the original label has no language or script code

The original label has a language and script code in the current dataset. In the JSON-LD, it's in the `originalLabel` property. The value of that label (without the script or language) is duplicated in the `label` property. This is not ideal, but that duplication was a tradeoff we made in order to 1) make the JSON easier to process, and 2) create RDF properties for `skos:prefLabel` values and `skos:altLabel` localized values.

Filtering by language works with any language applied to the period (original or alternate). All 1791 periods currently have English labels, whether for the original or alternate, which is indicated in the filtering interface. It would be definitely useful in a future version to differentiate between filtering original and alternate labels.

In terms of viewing the details of a specific period, I forgot to put the script tag for the original language. I will add that. Nothing has been lost.

**Comment by ptgolden** [comment]
fixed by 94845f5efd76a5b2e7210b36c9d0040cd89cfa6f
