### ISSUE TITLE
Strange behavior with patch submission: repeated new period

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#84]
I accepted a patch for the British Museum data that added the following period: http://n2t.net/ark:/99152/p08m57h4q9c

I then made some other changes to my local copy of the BM data, all having to do with spatial coverage (values that weren't parsed in the ingest). When I submitted a new patch, the submission included the edited spatial values normally, but it also included this, which seems to be the same period that has already been accepted into the canonical dataset above:

![image](https://cloud.githubusercontent.com/assets/4740995/9501721/81da25c2-4bf2-11e5-979d-78f4fde80eb7.png)

I can ignore this and submit the rest of the patch, but this probably needs attention.

**Comment by ptgolden** [comment]
In the backend where you submitted that patch, select "View submitted patches" from the menu, then click on "Refresh patch status". The reason it thinks that period is new is because it was assigned a different, permanent identifier when accepted into the canonical dataset. Hitting that "refresh patch status" button will make your local backend aware of that new identifier.

**Comment by atomrab** [comment]
Got it, worked. Thanks!
